services:
  gateway:
    build: .
    container_name: llm-gateway
    ports:
      - "8000:8000"
    environment:
      PROVIDER_MODE: ollama
      OLLAMA_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: tinyllama:latest
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://llm:llm@postgres:5432/llm_gateway
      ALLOW_ADMIN_RESET: "true"
      PROMETHEUS_URL: http://prometheus:9090
    depends_on:
      - postgres
      - redis

  ui:
    build:
      context: ./frontend
    container_name: llm-ui
    ports:
      - "5173:5173"
    environment:
      VITE_GATEWAY_URL: http://localhost:8000
      VITE_DEFAULT_MODEL: tinyllama:latest
    depends_on:
      - gateway

  postgres:
    image: postgres:16
    container_name: llm-postgres
    environment:
      POSTGRES_USER: llm
      POSTGRES_PASSWORD: llm
      POSTGRES_DB: llm_gateway
    ports:
      - "1312:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: llm-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: llm-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.1.0
    container_name: llm-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ALLOW_EMBEDDING: "true"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  pg_data:
  grafana_data:
